#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-$(CONFIG_MTK_CAM_CAL_IMX219_SUPPORT)			+= imx219otp.o
obj-y			+= imx219otp.o
